import AppKit
import Foundation
import os

private let monitorLogger = Logger(subsystem: "io.haunc.NovaClipboard", category: "ClipboardMonitor")

final class ClipboardMonitor {
    /// Pasteboard UTIs that indicate the source app wants its contents kept private.
    /// See Spec §7.1 and http://nspasteboard.org/.
    static let concealedUTIs: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.lastpass.copied"
    ]

    private let pasteboard: NSPasteboard
    private let pollInterval: TimeInterval
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Background queue for hashing and disk writes so large images don't block the 300ms poll
    /// or the main thread that owns SwiftData.
    private let processingQueue = DispatchQueue(
        label: "io.haunc.NovaClipboard.ClipboardMonitor.processing",
        qos: .utility
    )

    var onNewItem: ((ClipboardItem) -> Void)?

    init(pasteboard: NSPasteboard = .general, pollInterval: TimeInterval = 0.3) {
        self.pasteboard = pasteboard
        self.pollInterval = pollInterval
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        stop()
        let timer = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func pollNow() {
        poll()
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        handleChange()
    }

    private func handleChange() {
        let bundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        if hasConcealedType() {
            monitorLogger.info("Skipping change: pasteboard advertises concealed UTI")
            return
        }

        // Priority: file URL > image > text/link
        if let fileItem = readFileURLs(bundleID: bundleID) {
            onNewItem?(fileItem)
            return
        }
        if let imageData = readImageData() {
            processImageAsync(data: imageData, bundleID: bundleID)
            return
        }
        if let textItem = readText(bundleID: bundleID) {
            onNewItem?(textItem)
            return
        }
    }

    private func hasConcealedType() -> Bool {
        guard let types = pasteboard.types else { return false }
        for t in types {
            if ClipboardMonitor.concealedUTIs.contains(t.rawValue) { return true }
        }
        return false
    }

    private func readFileURLs(bundleID: String?) -> ClipboardItem? {
        guard let items = pasteboard.pasteboardItems else { return nil }
        var urls: [String] = []
        for item in items {
            if let str = item.string(forType: .fileURL),
               let url = URL(string: str), url.isFileURL {
                urls.append(url.absoluteString)
            }
        }
        guard !urls.isEmpty else { return nil }
        return ClipboardItem.file(urls: urls, sourceBundleID: bundleID)
    }

    /// Reads PNG/TIFF bytes off the pasteboard but defers hashing and disk writes — those run
    /// in `processImageAsync` so the polling loop and main thread stay responsive on big copies.
    private func readImageData() -> Data? {
        let pngType = NSPasteboard.PasteboardType("public.png")
        let tiffType = NSPasteboard.PasteboardType("public.tiff")

        if let png = pasteboard.data(forType: pngType) {
            return png
        }
        if let tiff = pasteboard.data(forType: tiffType),
           let rep = NSBitmapImageRep(data: tiff) {
            return rep.representation(using: .png, properties: [:])
        }
        return nil
    }

    private func processImageAsync(data: Data, bundleID: String?) {
        processingQueue.async { [weak self] in
            let id = UUID()
            let inline = data.count < ImageStore.inlineLimitBytes
            let path = inline ? nil : ImageStore.write(data: data, id: id)
            let checksum = Checksum.sha256(data)

            let sizeKB = Double(data.count) / 1024.0
            let preview = sizeKB < 1024
                ? String(format: "Image · %.0f KB", sizeKB)
                : String(format: "Image · %.1f MB", sizeKB / 1024.0)

            let item = ClipboardItem(
                id: id,
                type: .image,
                preview: preview,
                imageBlob: inline ? data : nil,
                imagePath: path,
                sourceBundleID: bundleID,
                checksum: checksum
            )
            DispatchQueue.main.async {
                self?.onNewItem?(item)
            }
        }
    }

    private func readText(bundleID: String?) -> ClipboardItem? {
        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return nil }
        if Self.isLikelyURL(text) {
            return ClipboardItem.link(text, sourceBundleID: bundleID)
        }
        return ClipboardItem.text(text, sourceBundleID: bundleID)
    }

    private static func isLikelyURL(_ s: String) -> Bool {
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, trimmed.count < 4096, !trimmed.contains(" ") else { return false }
        if let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "mailto"].contains(scheme) {
            return true
        }
        return false
    }
}
